package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/petermann-digital/quadlet-openrc/internal/generate"
	"github.com/petermann-digital/quadlet-openrc/internal/quadlet"
)

type options struct {
	input, output, podman, prefix string
	dry, strict, lint, clean      bool
}

func main() {
	cmd := "generate"
	args := os.Args[1:]
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		cmd = args[0]
		args = args[1:]
	}
	switch cmd {
	case "generate", "check", "lint":
		run(cmd, args)
	case "version", "--version", "-version":
		fmt.Println(generate.Version)
	case "help", "--help", "-h":
		usage()
	default:
		fatal(fmt.Errorf("unknown command %q", cmd))
	}
}
func usage() {
	fmt.Print(`quadlet-openrc 0.3 - stable CLI

Usage:
  quadlet-openrc generate [options]   Generate OpenRC services (default)
  quadlet-openrc check [options]      Parse and validate without writing
  quadlet-openrc lint [options]       Validate and report security findings
  quadlet-openrc version              Print version

Stable options:
  --input DIR          Quadlet directory (default /etc/containers/openrc)
  --output DIR         OpenRC directory (default /etc/init.d)
  --podman PATH        Podman executable (default /usr/bin/podman)
  --service-prefix P   Resource service prefix (default quadlet-)
  --dry-run            Print generated services
  --strict             Treat warnings as errors
  --lint               Include security lint in generate/check
  --clean              Remove stale files previously generated by this tool
`)
}
func run(cmd string, args []string) {
	fs := flag.NewFlagSet(cmd, flag.ExitOnError)
	o := options{}
	fs.StringVar(&o.input, "input", "/etc/containers/openrc", "input directory")
	fs.StringVar(&o.output, "output", "/etc/init.d", "output directory")
	fs.StringVar(&o.podman, "podman", "/usr/bin/podman", "podman path")
	fs.StringVar(&o.prefix, "service-prefix", "quadlet-", "resource service prefix")
	fs.BoolVar(&o.dry, "dry-run", false, "print output")
	fs.BoolVar(&o.strict, "strict", false, "warnings are errors")
	fs.BoolVar(&o.lint, "lint", false, "security lint")
	fs.BoolVar(&o.clean, "clean", false, "remove stale generated files")
	_ = fs.Parse(args)
	if cmd == "check" {
		o.dry = true
	}
	if cmd == "lint" {
		o.dry = true
		o.lint = true
	}
	files := load(o.input)
	g := generate.New()
	g.SourceDir = o.input
	g.Podman = o.podman
	g.ServicePrefix = o.prefix
	g.Register(files)
	for _, e := range generate.ValidateGraphWith(g, files) {
		fatal(e)
	}
	results := make([]generate.Result, 0, len(files))
	hadWarnings := false
	for _, q := range files {
		r, e := g.Generate(q)
		if e != nil {
			fatal(e)
		}
		ws := append([]string{}, r.Warnings...)
		if o.lint {
			ws = append(ws, generate.SecurityWarnings(q)...)
		}
		sort.Strings(ws)
		for _, w := range ws {
			fmt.Fprintf(os.Stderr, "warning: %s: %s\n", filepath.Base(q.Path), w)
			hadWarnings = true
		}
		results = append(results, r)
	}
	if o.strict && hadWarnings {
		fatal(fmt.Errorf("warnings encountered in strict mode"))
	}
	if cmd == "check" || cmd == "lint" {
		fmt.Fprintf(os.Stderr, "validated %d Quadlet file(s)\n", len(files))
		return
	}
	if o.dry {
		for _, r := range results {
			fmt.Printf("### %s\n%s\n", r.Service, r.Content)
		}
		return
	}
	if err := os.MkdirAll(o.output, 0755); err != nil {
		fatal(err)
	}
	keep := map[string]bool{}
	for _, r := range results {
		p := filepath.Join(o.output, r.Service)
		tmp := p + ".tmp"
		if err := os.WriteFile(tmp, []byte(r.Content), 0755); err != nil {
			fatal(err)
		}
		if err := os.Rename(tmp, p); err != nil {
			fatal(err)
		}
		keep[r.Service] = true
		fmt.Println(p)
	}
	if o.clean {
		entries, _ := os.ReadDir(o.output)
		for _, e := range entries {
			if keep[e.Name()] {
				continue
			}
			p := filepath.Join(o.output, e.Name())
			d, err := os.ReadFile(p)
			if err == nil && strings.Contains(string(d), "Generated by quadlet-openrc") {
				_ = os.Remove(p)
				fmt.Println("removed", p)
			}
		}
	}
}
func load(dir string) []*quadlet.File {
	entries, err := os.ReadDir(dir)
	if err != nil {
		fatal(err)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
	var files []*quadlet.File
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		ext := filepath.Ext(e.Name())
		if ext != ".container" && ext != ".network" && ext != ".volume" && ext != ".image" {
			continue
		}
		q, err := quadlet.Parse(filepath.Join(dir, e.Name()))
		if err != nil {
			fatal(err)
		}
		files = append(files, q)
	}
	if len(files) == 0 {
		fatal(fmt.Errorf("no supported Quadlet files found in %s", dir))
	}
	return files
}
func fatal(err error) { fmt.Fprintln(os.Stderr, "quadlet-openrc:", err); os.Exit(1) }
